<?xml version="1.0"?>
<doc>
<assembly>
<name>
Case.Subs.SuperTag
</name>
</assembly>
<members>
<member name="T:Case.Subs.SuperTag.My.Resources.Resources">
<summary>
  A strongly-typed resource class, for looking up localized strings, etc.
</summary>
</member>
<member name="P:Case.Subs.SuperTag.My.Resources.Resources.ResourceManager">
<summary>
  Returns the cached ResourceManager instance used by this class.
</summary>
</member>
<member name="P:Case.Subs.SuperTag.My.Resources.Resources.Culture">
<summary>
  Overrides the current thread's CurrentUICulture property for all
  resource lookups using this strongly typed resource class.
</summary>
</member>
<member name="P:Case.Subs.SuperTag.My.Resources.Resources.Case_Clearly">
<summary>
  Looks up a localized resource of type System.Drawing.Bitmap.
</summary>
</member>
<member name="P:Case.Subs.SuperTag.My.Resources.Resources.search">
<summary>
  Looks up a localized resource of type System.Drawing.Bitmap.
</summary>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsElement.IsChecked">
 <summary>
 Include Checked
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsElement.ElementFullName">
 <summary>
 Element Full Name 
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsElement.ElementObject">
 <summary>
 The Element
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsElement.#ctor(Autodesk.Revit.DB.Element)">
 <summary>
 Constructor
 </summary>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.#ctor(Autodesk.Revit.UI.ExternalCommandData)">
 <summary>
 Constructor
 </summary>
 <param name="c"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.GetAreasSpacesRooms">
 <summary>
 Get spatial elements
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.GetSymbolNames">
 <summary>
 Get All Symbol Names
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.GetTags">
 <summary>
 List of Tag Families
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.ScanCategories">
 <summary>
 Get a Sorted List of Categories in Use
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsSettings.GetViews">
 <summary>
 Get all qualifying views
 </summary>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsView.IsChecked">
 <summary>
 Check Include
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsView.ViewName">
 <summary>
 View Name
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsView.ViewLevel">
 <summary>
 Generation Level
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="P:Case.Subs.SuperTag.Data.clsView.ViewType">
 <summary>
 View Type
 </summary>
 <value></value>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsView.#ctor(Autodesk.Revit.DB.View)">
 <summary>
 Constructor
 </summary>
 <param name="v"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Data.clsView.GetViewElement">
 <summary>
 Get the View
 </summary>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="T:Case.Subs.SuperTag.Entry.A01A0A226EBE4CD89D655C55B997650F">
 <summary>
 Revit 2022 Command Class 
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Entry.A01A0A226EBE4CD89D655C55B997650F.Execute(Autodesk.Revit.UI.ExternalCommandData,System.String@,Autodesk.Revit.DB.ElementSet)">
 <summary>
 Command Entry Point
 </summary>
 <param name="commandData"></param>
 <param name="message"></param>
 <param name="elements"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.#ctor(Case.Subs.SuperTag.Data.clsSettings)">
 <summary>
 Form
 </summary>
 <param name="s"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.SetFormViz(Case.Subs.SuperTag.Form_Main.EnumFormViz)">
 <summary>
 Set appearance of controls based on state
 </summary>
 <param name="fv"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.Setup">
 <summary>
 For Obfuscation
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.UpdateFamiliesList(System.Boolean)">
 <summary>
 List of Families Subject for Tagging
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.UpdateTagFamilies">
 <summary>
 Update Tag Families List
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.UpdateViews(System.Boolean)">
 <summary>
 Load the List of Views into the Form
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.TagElementsInViews">
 <summary>
 Tag the Elements
 </summary>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.GetMidpoint(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
 <summary>
 Midpoint of two points
 </summary>
 <param name="pt1"></param>
 <param name="pt2"></param>
 <returns></returns>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonOk_Click(System.Object,System.EventArgs)">
 <summary>
 Commit
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonCancel_Click(System.Object,System.EventArgs)">
 <summary>
 Close
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonSymbolsCheckAll_Click(System.Object,System.EventArgs)">
 <summary>
 Symbols - All
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonSymbolsCheckNone_Click(System.Object,System.EventArgs)">
 <summary>
 Symbols - None
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonViewsCheckAll_Click(System.Object,System.EventArgs)">
 <summary>
 Symbols - All
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonViewsCheckNone_Click(System.Object,System.EventArgs)">
 <summary>
 Symbols - None
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.PictureBoxLogo_Click(System.Object,System.EventArgs)">
 <summary>
 Launch Site
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
<member name="M:Case.Subs.SuperTag.Form_Main.ButtonHelp_Click(System.Object,System.EventArgs)">
 <summary>
 Help
 </summary>
 <param name="sender"></param>
 <param name="e"></param>
 <remarks></remarks>
</member>
</members>
</doc>
